server:
  port: 9009
  
spring:
  livereload:
    enabled: true
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
       format_sql: true
       show_sql: true
       dialect: org.hibernate.dialect.MySQL8Dialect
        
  datasource:
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
    url: jdbc:mysql://semisemi.c6b0upyu6miu.ap-northeast-2.rds.amazonaws.com:3306/semisemi?serverTimeZone=Asia/Seoul
    username: admin
    password: 123456789
    
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

  logging:
    level:
      me.silvernine: debug
      root: warn
      shutup.code.scrt: debug

  mybatis:
    type-aliases-package: com.bit.fnl.mapper, com.bit.fnl.dto
    mapper-locations:
      - /mapper/**/*.xml
